spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/chat-app
    username: root
    password: MB0,%^g4Sk@#^.}
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG